
package Mochila;

import java.util.List;
import java.util.LinkedList;
import javax.swing.JOptionPane;

public class MochilaFrame extends javax.swing.JFrame {

    int peso[];
    int valor[];
    int capacidad;
   
    List listaObjetos;
    int Maximo_Beneficio;


    /** Creates new form MochilaFrame */
    public MochilaFrame() {
        initComponents();
        listaObjetos=new LinkedList();   
        setLocationRelativeTo(null);
       
       jTxt_peso.setEnabled(false);
       jTxt_beneficio.setEnabled(false);
       jB_Okobjeto.setEnabled(false);
       jTxtA_objetos.setEnabled(false);
       jB_mostrar.setEnabled(false);
       
       jTxA_tabla.setEnabled(false);
       jB_optimizacion.setEnabled(false);
  
       

       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxt_peso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxt_beneficio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jB_Okobjeto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtA_objetos = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxt_capacidad = new javax.swing.JTextField();
        jB_Okmochila = new javax.swing.JButton();
        jB_mostrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxA_tabla = new javax.swing.JTextArea();
        jB_optimizacion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmos Voraces: Mochila");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setText("PESO :");

        jTxt_peso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setText("BENEFICIO :");

        jTxt_beneficio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setText("INGRESO DE OBJETOS");

        jB_Okobjeto.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jB_Okobjeto.setText("LLENAR");
        jB_Okobjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OkobjetoActionPerformed(evt);
            }
        });

        jTxtA_objetos.setColumns(20);
        jTxtA_objetos.setRows(5);
        jScrollPane2.setViewportView(jTxtA_objetos);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel4.setText("CAPACIDAD DE LA MOCHILA");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel5.setText("CAPACIDAD :");

        jTxt_capacidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jB_Okmochila.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jB_Okmochila.setText("Click");
        jB_Okmochila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OkmochilaActionPerformed(evt);
            }
        });

        jB_mostrar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jB_mostrar.setText("MOSTRAR OBJETOS");
        jB_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_mostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTxt_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jB_Okmochila)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxt_peso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxt_beneficio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_Okobjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jB_mostrar)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jB_Okmochila)
                    .addComponent(jTxt_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxt_beneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jB_Okobjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_mostrar)
                .addGap(68, 68, 68))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 300, 410));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SOLUCION "));

        jTxA_tabla.setColumns(20);
        jTxA_tabla.setRows(5);
        jScrollPane1.setViewportView(jTxA_tabla);

        jB_optimizacion.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jB_optimizacion.setText("LLENAR MOCHILA");
        jB_optimizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_optimizacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_optimizacion)
                .addGap(90, 90, 90))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_optimizacion)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 320, 410));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_OkobjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OkobjetoActionPerformed

    try{

        int p=Integer.parseInt(jTxt_peso.getText());
        int v=Integer.parseInt(jTxt_beneficio.getText());
        Objeto aux=new Objeto(p,v);
        listaObjetos.add(aux);
        jTxt_beneficio.setText("");
        jTxt_peso.setText("");

    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, " Favor ingrese un objeto!! ", "Error", 0);
    }
    }//GEN-LAST:event_jB_OkobjetoActionPerformed

    private void jB_OkmochilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OkmochilaActionPerformed
    try{
        capacidad=Integer.parseInt(jTxt_capacidad.getText());
        jTxt_capacidad.setText("");
    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Por Favor ingrese la capacidad de la mochila ", "Error", 0);
    }
      jTxt_peso.setEnabled(true);
       jTxt_beneficio.setEnabled(true);
       jB_Okobjeto.setEnabled(true);
       jTxtA_objetos.setEnabled(true);
       jB_mostrar.setEnabled(true);
       
       
       jTxt_capacidad.setEditable(false);
       jB_Okmochila.setEnabled(false);
    
    }//GEN-LAST:event_jB_OkmochilaActionPerformed

    private void jB_optimizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_optimizacionActionPerformed
      jTxA_tabla.setEnabled(true);
      
        peso=new int[listaObjetos.size()];
        valor=new int[listaObjetos.size()];
        for(int i=0;i<listaObjetos.size();i++){
            peso[i]=((Objeto)listaObjetos.get(i)).getPeso();
            valor[i]=((Objeto)listaObjetos.get(i)).getValor();
        }
        Mochila miMochila = new Mochila(peso, valor, capacidad);
        Maximo_Beneficio = miMochila.elegirObjetos();
        miMochila.Componer();
        jTxA_tabla.setText("");
        jTxA_tabla.append("\n    Objetos elegidos\n"+"  \n\n");
        jTxA_tabla.append("    Obj\tPeso\tBeneficio  \n");
        for (int i = 1; i<=peso.length; i++)
            if (miMochila.getElegido(i)==1){
                jTxA_tabla.append("      "+i+"\t  "+miMochila.getPeso(i)+
                        "\t    "+ miMochila.getValor(i)+"\n");
        }
        jTxA_tabla.append("\n    Maximo beneficio :  "+Maximo_Beneficio+"\n");
    }//GEN-LAST:event_jB_optimizacionActionPerformed

    private void jB_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_mostrarActionPerformed
   
        jB_optimizacion.setEnabled(true);
    
        jTxtA_objetos.setText("");
        jTxtA_objetos.append("\n  ** Objetos Registrados **\n\n");
        jTxtA_objetos.append("   Objeto\tPeso\tBeneficio  \n");
        for (int i=0; i<listaObjetos.size(); i++){
            jTxtA_objetos.append("        "+(i+1)+"\t  "+((Objeto)listaObjetos.get(i)).getPeso()
                                +"\t    "+((Objeto)listaObjetos.get(i)).getValor()+"\n");
        }

    }//GEN-LAST:event_jB_mostrarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MochilaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Okmochila;
    private javax.swing.JButton jB_Okobjeto;
    private javax.swing.JButton jB_mostrar;
    private javax.swing.JButton jB_optimizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTxA_tabla;
    private javax.swing.JTextArea jTxtA_objetos;
    private javax.swing.JTextField jTxt_beneficio;
    private javax.swing.JTextField jTxt_capacidad;
    private javax.swing.JTextField jTxt_peso;
    // End of variables declaration//GEN-END:variables

}
