/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista.Tienda;

import Entidad.Complementos;
import Entidad.Laptop;
import Entidad.Usuario;
import Negocio.GestorPrincipal;
import static UtilJava.ClaseCargarImagen.PasarImagenIcon2;
import static Vista.Tienda.FrameIniciarCesion.usuarioregistrado;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author RIKARDO
 */
public class JMiniPanelComplemntos extends javax.swing.JPanel {

    /**
     * Creates new form JMiniPanel
     */
    private Usuario usuu;
    private Complementos lap;
    public JMiniPanelComplemntos(Complementos lap) {
        this.lap=lap;
        usuu=usuarioregistrado;
        initComponents();
        this.setBorder(BorderFactory.createTitledBorder(lap.getNombre()+": "+lap.getMarca() ));
        jLabel2.setIcon(PasarImagenIcon2(lap.getFotovuelta()));
        jLabel3.setText("$/ "+lap.getPrecio());
        jTextArea1.setText(lap.getSerie()+"\n"+lap.getMarca());
    }


    
    public void IniciarComponentes(){
        jLabel2= new JLabel(PasarImagenIcon2(lap.getFotovuelta()));
        jButton1= new JButton("$/ "+lap.getPrecio());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(0, 0, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_carro.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 73, 50));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 120, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 65, 23));

        jTextArea1.setColumns(15);
        jTextArea1.setRows(3);
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, 160, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(usuu==null){
            JOptionPane.showMessageDialog(this,"Porfavor Inicie Secion !!" , null, JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, lap.getSerie(), "producto", WIDTH);
             TiendaVirtual.lscarrito.add(lap);
            boolean e=GestorPrincipal.getGestorComple().ModificarPref(lap.getPreferencia(), lap.getSerie(),0.2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
