/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista.Tienda;

import Entidad.Laptop;

import static Vista.Tienda.TiendaVirtual.lsLap;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeremy
 */
public class VistaLaptop extends javax.swing.JPanel {

    /**
     * Creates new form VistaPC
     */
    private int desli;
    static Laptop lappatodo;
    
    public VistaLaptop() {
        initComponents();
        setBounds(0, 0, 242, 519);
        etiquetaValor.setText(jSdeslisador.getValue()+"");
    }
    
    class Informacion{
        private String marca;
        private Double precio;
        private int ram;
        private int discoduro;
        private String so;

        public Informacion(String marca, Double precio, int ram, int discoduro, String so) {
            this.marca = marca;
            this.precio = precio;
            this.ram = ram;
            this.discoduro = discoduro;
            this.so = so;
        }

        public Informacion() {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSdeslisador = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etiquetaValor = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Caracteristicas "));

        jLabel1.setText("Marca");

        jLabel2.setText("Precio Maximo");

        jSdeslisador.setMajorTickSpacing(100);
        jSdeslisador.setMaximum(5000);
        jSdeslisador.setMinimum(1000);
        jSdeslisador.setPaintTicks(true);
        jSdeslisador.setValue(3000);
        jSdeslisador.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSdeslisadorStateChanged(evt);
            }
        });

        jLabel3.setText("1000");

        jLabel4.setText("5000");

        etiquetaValor.setText("0.00");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Ubuntu", "Windows", "Mac" }));

        jLabel5.setText("S.O ");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Tamaño ");

        jLabel7.setText("Ram");

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setText("2");

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setText("4");

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setText("8");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "10''", "12''", "14''", "16''" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "toshiba", "asus", "hp", "lenovo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(etiquetaValor)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSdeslisador, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4)))
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton10))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSdeslisador, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSdeslisadorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSdeslisadorStateChanged
        etiquetaValor.setText(jSdeslisador.getValue()+"");
        desli=jSdeslisador.getValue();
    }//GEN-LAST:event_jSdeslisadorStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String marca,so,tamaño;
        int ram=0,i=0;
        double precio;
        boolean bol = false;
        ArrayList<Laptop> profin = new ArrayList<>();
        Laptop lapaux= new Laptop();
        System.out.println(lsLap.size());
        if(jRadioButton8.isSelected())
            ram=Integer.parseInt(jRadioButton8.getText());
        else
            if(jRadioButton9.isSelected())
                ram=Integer.parseInt(jRadioButton9.getText());
            else
                if(jRadioButton10.isSelected())
                    ram=Integer.parseInt(jRadioButton10.getText());
        
        
        if(jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || jComboBox2.getSelectedItem().toString().equalsIgnoreCase("Seleccione")
                || ram==0 || jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Seleccione")){
            JOptionPane.showMessageDialog(this, "Revise todos los campos", "REGISTRO", JOptionPane.ERROR_MESSAGE);
        }else{
            so=jComboBox1.getSelectedItem().toString();
            marca=jComboBox3.getSelectedItem().toString();
            tamaño=jComboBox2.getSelectedItem().toString();
            precio=desli;
            lappatodo= new Laptop(so, tamaño, ram, null, precio, marca, null, null, 0, null);
            
            
            while(i<lsLap.size()){
                lapaux = lsLap.get(i);
                if(lappatodo.getSO().equalsIgnoreCase(lapaux.getSO())&& lappatodo.getMarca().equalsIgnoreCase(lapaux.getMarca())&& 
                   lappatodo.getTamano().equalsIgnoreCase(lapaux.getTamano())&& lappatodo.getRam()==lapaux.getRam()&&lappatodo.getPrecio()<=lapaux.getPrecio()){
                    profin.add(lapaux);
                    bol=true;
                }
                i++;
            }
            
            TiendaVirtual.LimpiaPanel();
            if(bol){
                TiendaVirtual.MostrarProductos(profin);
            }else{
                JOptionPane.showMessageDialog(this, "NO SE ENCONTRARON LAPTOPS CON ESAS CARACTERISTICAS", "LO SENTIMOS :c", JOptionPane.PLAIN_MESSAGE);
            }
            TiendaVirtual.ActualizaPanel();
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel etiquetaValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSlider jSdeslisador;
    // End of variables declaration//GEN-END:variables
}
