/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package estrellitas;

import java.awt.Event;

/**
 *
 * @author RIKARDO
 */
public class PanelEstrellitas extends javax.swing.JPanel {

    /**
     * Creates new form PanelEstrellitas
     */
    private int valor;
    private int val2;
    
    public PanelEstrellitas() {
        valor=0;
        val2=0;
        initComponents();
        setVisible(true);
        setBounds(2, 2, 174, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(150, 28));
        setPreferredSize(new java.awt.Dimension(174, 28));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EnteredB1(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 30, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 30, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 30, -1));
    }// </editor-fold>//GEN-END:initComponents

    public int getValor() {
        return valor;
    }

    public void setValor(int val) {
        valor = val;
    }

    
    
    
    private void EnteredB1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnteredB1
        val2=1;
        repaint(val2);
//        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
//        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
//        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
//        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
    }//GEN-LAST:event_EnteredB1

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        val2=2;
        repaint(val2);
//        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
//        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
//        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        val2=3;
        repaint(3);
//        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
//        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        val2=4;
        repaint(val2);
//        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        val2=5;
        repaint(val2);
//            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//            jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
//            jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
    }//GEN-LAST:event_jButton5MouseEntered

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
    }//GEN-LAST:event_formMouseEntered

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        setValor(3);
        repaint(valor);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        setValor(1);
        repaint(valor);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        setValor(2);
        repaint(valor);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        setValor(4);
        repaint(valor);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        setValor(5);
        repaint(valor);
    }//GEN-LAST:event_jButton5MouseClicked

    public void verifica(int valo){
        if(valo==0){
            limpiarBotones();
        }else{
            repaint(val2);
        }
    }
    public void repaint(int valor){
        if(valor==1){
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        }
        if(valor==2){
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        }
        if(valor==3){
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        }
        if(valor==4){
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        }
        if(valor==5){
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("estrella.png")));
        }
        
    }
    public void limpiarBotones(){
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/31g.png")));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
