package Vista.Admin;

import Entidad.Pc;
import Negocio.GestorPrincipal;
import ReportePdf.Reportes;
import UtilJava.ClaseCargarImagen;
import static UtilJava.ClaseCargarImagen.PasarImagenIcon;
import java.io.FileInputStream;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nelsoncuenta
 */
public class JframeRegistroPc extends javax.swing.JFrame {

    /**
     * Creates new form JframeRegistro_Usuario
     */
    DefaultTableModel modelo;
    String data[][] = {};
    String columna[] = {"serie", "marca", "modelo", "so", "descripcion", "ram", "Disco Duro", "precio"};

    public FileInputStream foto;
    Pc pc=null;
    private Icon alerta;

    public JframeRegistroPc() {
        initComponents();
        pc = new Pc();
        modelo = new DefaultTableModel(data, columna);
        jTable1.setModel(modelo);
        //usu =new Usuario(nombre, apepater, apemater, edad, celular, dni, longitud, correo, foto, apepater, usuario);
        CargandoTablaPcs();
        setLocationRelativeTo(null);
        jButton10ActualizaBD.setEnabled(false);
        jButton9.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxfSerie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxfModelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxfPrecio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxfaDescripcion = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10ActualizaBD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 0, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 30)); // NOI18N
        jLabel1.setText("REGISTRO PC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 360, 41));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 82, 1158, 10));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null), "Datos de la pc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Serie");

        jtxfSerie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxfSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfSerieActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Marca");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Modelo");

        jtxfModelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("RAM");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Precio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Descripcion");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Disco Duro");

        jtxfPrecio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfPrecioActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pc.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/picture-24.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("SUBIR FOTO ");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rotate-32.png"))); // NOI18N
        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtxfaDescripcion.setColumns(20);
        jtxfaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jtxfaDescripcion);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("SO");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Lenovo", "Toshiba", "hp", "asus", "Dell" }));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("250");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("500");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("1");

        jLabel8.setText("T");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Ubuntu", "Windows", "Mac", "Personalizado" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("4");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("8");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("16");

        jLabel9.setText("GB");

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jRadioButton7.setText("ACTUALIZAR DATOS  B.D");
        jRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton7MousePressed(evt);
            }
        });
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jRadioButton8.setText("ACTUALIZAR FOTO B.D");
        jRadioButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtxfPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(49, 49, 49)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton2)
                                        .addComponent(jRadioButton3)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 98, 840, 310));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search-24.png"))); // NOI18N
        jButton6.setText("BUSCAR /DNI");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, 34));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close-24.png"))); // NOI18N
        jButton3.setText("SALIR ");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 110, 34));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_user-32.png"))); // NOI18N
        jButton1.setText("REGISTRAR");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, 30));

        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField10MousePressed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 126, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cup-24.png"))); // NOI18N
        jButton7.setText("ELIMINAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 130, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adobe_Acrobat.png"))); // NOI18N
        jButton8.setText("VER REPORTE PDF");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 51));
        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 25)); // NOI18N
        jLabel14.setText("Lista de Pc's");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 170, 41));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 471, 1158, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 0));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 1040, 150));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mysql.png"))); // NOI18N
        jButton9.setText("ACTUALIZA FOTO B.D");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 140, 160, -1));

        jButton10ActualizaBD.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton10ActualizaBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mysql2.png"))); // NOI18N
        jButton10ActualizaBD.setText("ACTUALIZA DATOS B.D");
        jButton10ActualizaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActualizaBDActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10ActualizaBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 210, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CargandoTablaPcs() {
        int j = 0;
        ArrayList<Pc> lsPc = GestorPrincipal.getGestorPc().lsPc();
        if (lsPc==null) {
            JOptionPane.showMessageDialog(this, "No hay ningun producto!!");
        } else {
            Pc pc = null;
           // if (lsPc.get(0) != null) {
                for (int i = 0; i < lsPc.size(); i++) {
                    pc = lsPc.get(i);
                    String b[] = {
                        pc.getSerie(),
                        pc.getMarca(),
                        pc.getModelo(),
                        pc.getSO(),
                        pc.getDescripcion(),
                        String.valueOf(pc.getRam()),
                        String.valueOf(pc.getDiscoDuro()),
                        String.valueOf(pc.getPrecio()),};
                    modelo.addRow(b);
                }

//            } else {
//                System.out.println("por est es el error");
//            }

        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ram=0,discoduro=0;
        
        if(jRadioButton1.isSelected())
            discoduro=Integer.parseInt(jRadioButton1.getText());
        else
            if(jRadioButton2.isSelected())
                discoduro=Integer.parseInt(jRadioButton2.getText());
            else
                if(jRadioButton3.isSelected())
                    discoduro=Integer.parseInt(jRadioButton3.getText());
        
        if(jRadioButton4.isSelected())
            ram=Integer.parseInt(jRadioButton4.getText());
        else
            if(jRadioButton5.isSelected())
                ram=Integer.parseInt(jRadioButton5.getText());
            else
                if(jRadioButton6.isSelected())
                    ram=Integer.parseInt(jRadioButton6.getText());
//        String s=buttonGroup1.getSelection().getActionCommand().toString();
//        System.out.println(s);
        
        if(ram==0|| discoduro==0|| jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || jComboBox2.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || discoduro==0 || ram==0){
            JOptionPane.showMessageDialog(this, "Llene todos los campos", "REGISTRO", JOptionPane.ERROR_MESSAGE);
        }else{
        pc.setSerie(jtxfSerie.getText());
        pc.setPrecio(Double.parseDouble(jtxfPrecio.getText()));
        pc.setMarca(jComboBox1.getSelectedItem().toString());
        pc.setModelo(jtxfModelo.getText());
        pc.setSO(jComboBox2.getSelectedItem().toString());
        pc.setDescripcion(jtxfaDescripcion.getText());
        pc.setRam(ram);
        pc.setDiscoDuro(discoduro);
        pc.setPreferencia(1);
        
        boolean estado = GestorPrincipal.getGestorPc().RegistrarPc(pc);
        if (estado) {
            JOptionPane.showMessageDialog(this, "Registro Exitoso!!");
        }
        // vamos a agregar los datos en la tabla 

        String a[] = {jtxfSerie.getText(),
            jComboBox1.getSelectedItem().toString(),
            jtxfModelo.getText(),
            jComboBox2.getSelectedItem().toString(),
            jtxfaDescripcion.getText(),
            String.valueOf(ram),
            String.valueOf(discoduro),
            jtxfPrecio.getText()
        };
        modelo.addRow(a);
       
        limpiarCampos();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        Usuario usu;
//        int BusqueDni = Integer.parseInt(jTextField10.getText());
//        try {
//         usu =GestorPrincipal.getGestorProducto().
//            ///.-------
//            jtxfSerie.setText(String.valueOf(usu.getDni()));
//            jtxfMarca.setText(usu.getNombre());
//            jtxfModelo.setText(usu.getApell_paterno());
//            jtxfRam.setText(usu.getApell_materno());
//            jtxfPrecio.setText(String.valueOf(usu.getCelular()));
//            jtxfDiscoDuro.setText(String.valueOf(usu.getEdad()));
//
//            jtxfTamaño.setText(usu.getUser());
//            jtxfSO.setText(usu.getPassword());
//            jLabel11.setIcon(PasarImagenIcon(usu.getFotoVuelta(), jLabel11));
//        } catch (Exception e) {
//
//            JOptionPane.showMessageDialog(null, "El DNI ingresado no esta registrado \n"
//                    + "   en la base de Datos!!!", "Error", JOptionPane.ERROR_MESSAGE, error);
//        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        boolean estado = false;
        int filaSelec = jTable1.getSelectedRow();
        String SerieTabla = modelo.getValueAt(filaSelec,0).toString();
        //int dniTabla= (int) modelo.getValueAt(filaSelec,0);

        if (filaSelec == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una Fila!!", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                int resp = JOptionPane.showConfirmDialog(this, "¿ Desea eliminar la Fila?", "Eliminar", JOptionPane.YES_NO_OPTION);
                if (resp == JOptionPane.YES_OPTION) {
                    modelo.removeRow(filaSelec);
                    estado = GestorPrincipal.getGestorPc().EliminarPc(SerieTabla);
                    if (estado) {
                        JOptionPane.showMessageDialog(this, "Se Elimino !!! la Fila");
                    }

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No pudo eliminar la Fila!!!!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
Reportes.ExportarReportes("pc.jrxml");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MousePressed
        limpiarCampos();
        this.jButton1.setEnabled(true);
        this.jButton6.setEnabled(true);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/laptop.png")));

    }//GEN-LAST:event_jTextField10MousePressed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

// TODO add your handling code here:
        Pc pc;
        limpiarCampos();
        this.jButton1.setEnabled(false);
        this.jButton6.setEnabled(false);
        try {
            int fila = jTable1.getSelectedRow();

            String TablaSerie = (String) modelo.getValueAt(fila, 0);
            pc = GestorPrincipal.getGestorPc().BuscarPc(TablaSerie);
            jtxfSerie.setText(pc.getSerie());
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {pc.getMarca()}));
            jtxfModelo.setText(pc.getModelo());
            jtxfaDescripcion.setText(pc.getDescripcion());
            jtxfPrecio.setText(String.valueOf(pc.getPrecio()));
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {pc.getSO()}));
            jLabel11.setIcon(PasarImagenIcon(pc.getFotovuelta(), jLabel11));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecciones solo una Fila!!", "Alerta", JOptionPane.WARNING_MESSAGE);

        }
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiarCampos();
        jTextField10.setText("");
        this.jButton1.setEnabled(true);
        this.jButton6.setEnabled(true);

        // TODO add your handling code h

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ClaseCargarImagen.CargandoImagenProducto(pc, jLabel11, jPanel2);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jtxfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxfPrecioActionPerformed

    private void jtxfSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxfSerieActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        boolean modificado=false;
        int fila = jTable1.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Selecciones una fila","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
        else {

            String serieTabla = jTable1.getValueAt(fila,0).toString();
            int ordenPc= GestorPrincipal.getGestorPc().OrdenPc(serieTabla);
            
int ram=0,discoduro=0;
        
        if(jRadioButton1.isSelected())
            discoduro=Integer.parseInt(jRadioButton1.getText());
        else
            if(jRadioButton2.isSelected())
                discoduro=Integer.parseInt(jRadioButton2.getText());
            else
                if(jRadioButton3.isSelected())
                    discoduro=Integer.parseInt(jRadioButton3.getText());
        
        if(jRadioButton4.isSelected())
            ram=Integer.parseInt(jRadioButton4.getText());
        else
            if(jRadioButton5.isSelected())
                ram=Integer.parseInt(jRadioButton5.getText());
            else
                if(jRadioButton6.isSelected())
                    ram=Integer.parseInt(jRadioButton6.getText());
        
        pc.setSerie(jtxfSerie.getText());
        pc.setPrecio(Double.parseDouble(jtxfPrecio.getText()));
        pc.setMarca(jComboBox1.getSelectedItem().toString());
        pc.setModelo(jtxfModelo.getText());
        pc.setSO(jComboBox2.getSelectedItem().toString());
        pc.setDescripcion(jtxfaDescripcion.getText());
        pc.setRam(ram);
        pc.setDiscoDuro(discoduro);

            modificado = GestorPrincipal.getGestorPc().ModificarPcConFoto(pc,ordenPc);

            // modificando la tabla de Laptops
            //serie
            jTable1.setValueAt(jtxfSerie.getText(),fila,0);
            //marca
            jTable1.setValueAt(jComboBox1.getSelectedItem().toString(),fila,1);
            //modelo
            jTable1.setValueAt(jtxfModelo.getText(),fila,2);
            // so
            jTable1.setValueAt(jComboBox2.getSelectedItem().toString(),fila,3);
            //descripcion
            jTable1.setValueAt(jtxfaDescripcion.getText(), fila, 4);
            //ram
            jTable1.setValueAt(ram, fila, 5);
            //discoduro
            jTable1.setValueAt(discoduro,fila, 6);
            //precio
            jTable1.setValueAt(jtxfPrecio.getText(),fila,7);
            if(modificado){
                JOptionPane.showMessageDialog(this,"Moficacion de los Datos Exitoso!!!!");}

            // limpiamos todo

            limpiarCampos();
            this.jtxfSerie.requestFocus();
            jButton6.setEnabled(true);
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActualizaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActualizaBDActionPerformed
        // TODO add your handling code here:
         boolean modificado=false;
        int fila = jTable1.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Selecciones una fila","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
        else {

            String serieTabla = jTable1.getValueAt(fila,0).toString();
            int ordenPc= GestorPrincipal.getGestorPc().OrdenPc(serieTabla);
            
int ram=0,discoduro=0;
        
        if(jRadioButton1.isSelected())
            discoduro=Integer.parseInt(jRadioButton1.getText());
        else
            if(jRadioButton2.isSelected())
                discoduro=Integer.parseInt(jRadioButton2.getText());
            else
                if(jRadioButton3.isSelected())
                    discoduro=Integer.parseInt(jRadioButton3.getText());
        
        if(jRadioButton4.isSelected())
            ram=Integer.parseInt(jRadioButton4.getText());
        else
            if(jRadioButton5.isSelected())
                ram=Integer.parseInt(jRadioButton5.getText());
            else
                if(jRadioButton6.isSelected())
                    ram=Integer.parseInt(jRadioButton6.getText());
        
        pc.setSerie(jtxfSerie.getText());
        pc.setPrecio(Double.parseDouble(jtxfPrecio.getText()));
        pc.setMarca(jComboBox1.getSelectedItem().toString());
        pc.setModelo(jtxfModelo.getText());
        pc.setSO(jComboBox2.getSelectedItem().toString());
        pc.setDescripcion(jtxfaDescripcion.getText());
        pc.setRam(ram);
        pc.setDiscoDuro(discoduro);

            modificado = GestorPrincipal.getGestorPc().ModificarPcSinFoto(pc,ordenPc);

            // modificando la tabla de Laptops
            //serie
            jTable1.setValueAt(jtxfSerie.getText(),fila,0);
            //marca
            jTable1.setValueAt(jComboBox1.getSelectedItem().toString(),fila,1);
            //modelo
            jTable1.setValueAt(jtxfModelo.getText(),fila,2);
            // so
            jTable1.setValueAt(jComboBox2.getSelectedItem().toString(),fila,3);
            //descripcion
            jTable1.setValueAt(jtxfaDescripcion.getText(), fila, 4);
            //ram
            jTable1.setValueAt(ram, fila, 5);
            //discoduro
            jTable1.setValueAt(discoduro,fila, 6);
            //precio
            jTable1.setValueAt(jtxfPrecio.getText(),fila,7);
            if(modificado){
                JOptionPane.showMessageDialog(this,"Moficacion de los Datos Exitoso!!!!");}

            // limpiamos todo

            limpiarCampos();
            this.jtxfSerie.requestFocus();
            jButton6.setEnabled(true);
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton10ActualizaBDActionPerformed

    private void jRadioButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton7MousePressed

        jButton5.setEnabled(false);
        jButton9.setEnabled(false);
        jButton10ActualizaBD.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7MousePressed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton8MousePressed
        jButton9.setEnabled(true);
        jButton5.setEnabled(true);
        jButton10ActualizaBD.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8MousePressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    public void limpiarCampos() {
        this.jtxfSerie.setText("");
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Lenovo", "Toshiba", "hp", "asus", "Dell" }));
        this.jtxfModelo.setText("");
        buttonGroup1.isSelected(null);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Ubuntu", "Windows", "Mac", "Personalizado" }));
        this.jtxfPrecio.setText("");
        this.jtxfaDescripcion.setText("");
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/laptop.png")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeRegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeRegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeRegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeRegistroPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeRegistroPc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10ActualizaBD;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jtxfModelo;
    private javax.swing.JTextField jtxfPrecio;
    private javax.swing.JTextField jtxfSerie;
    private javax.swing.JTextArea jtxfaDescripcion;
    // End of variables declaration//GEN-END:variables
}
