

package Vista.Admin;
import ConexionMysql.Dao;
import Entidad.Laptop;
import Negocio.GestorPrincipal;
import ReportePdf.Reportes;
import static UtilJava.ClaseCargarImagen.CargandoImagenProducto;
import static UtilJava.ClaseCargarImagen.PasarImagenIcon;
import UtilJava.Validaciones;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
 
/**
 *
 * @author nelsoncuenta
 */
public class JframeRegistoLaptops extends javax.swing.JFrame {
       
    /**
     * Creates new form JframeRegistro_Usuario
     */
    DefaultTableModel  modelo;
    String data[][]={};
    
    String columna[]={"serie","Marca","Modelo","Descripcion","SO","tamaño","Ram","Precio","Preferencia"};
   
           
    public int longitud, preferencia,ram;
    public Double precio;
    public String serie, marca,modeloLap,descripcion,so,tamano;
    public  FileInputStream foto ;
    Laptop usu;
 
 
    public JframeRegistoLaptops() {
        initComponents();
        usu = new Laptop();
        modelo = new  DefaultTableModel(data, columna);
        jTable2.setModel(modelo);
        //usu =new Usuario(nombre, apepater, apemater, edad, celular, dni, longitud, correo, foto, apepater, usuario);
        CargandoTablaLaptop2();
        setLocationRelativeTo(null);
        Validaciones.SoloNumeros(jTextField8);
        jTextField5.setEnabled(false);
        jButton4.setEnabled(false);
        jButton10ActualizaBD.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton10ActualizaBD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 0, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setText("   ADMINISTRAR REGISTROS LAPTOP's");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 480, 41));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 82, 1158, 10));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null), "Registro de Laptops", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("SERIE");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("MARCA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("MODELO");

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("PREFERENCIA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("DESCRIPCION");

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("TAMAÑO");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("PRECIO:");

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("RAM");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("FOTO DE LAPTOP");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/laptop.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/picture-24.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("SUBIR FOTO ");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rotate-32.png"))); // NOI18N
        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documents_folder-24.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contacts-24.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contacts-24.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("SO");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "toshiba", "asus", "hp", "lenovo" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "10''", "12''", "14''", "16''" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Ubuntu", "Windows", "Mac" }));

        jLabel17.setText("S/.");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "2", "4", "8" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jRadioButton1.setText("ACTUALIZAR FOTO B.D");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton1MousePressed(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jRadioButton2.setText("ACTUALIZAR DATOS  B.D");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton2MousePressed(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton2)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel17)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1)
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 61, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel16)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel20)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel17)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel9))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 98, 800, 280));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search-24.png"))); // NOI18N
        jButton6.setText("BUSCAR /SERIE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 150, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close-24.png"))); // NOI18N
        jButton3.setText("SALIR ");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 110, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_user-32.png"))); // NOI18N
        jButton1.setText("REGISTRAR");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, 40));

        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField10MousePressed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cup-24.png"))); // NOI18N
        jButton7.setText("ELIMINAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 120, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adobe_Acrobat.png"))); // NOI18N
        jButton8.setText("REPORTES");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, 40));

        jLabel14.setBackground(new java.awt.Color(255, 255, 51));
        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 25)); // NOI18N
        jLabel14.setText("Lista de Usuarios");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 441, 239, 41));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 432, 1158, 3));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 1000, 150));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mysql.png"))); // NOI18N
        jButton4.setText("ACTUALIZA FOTO B.D");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        jButton10ActualizaBD.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton10ActualizaBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mysql2.png"))); // NOI18N
        jButton10ActualizaBD.setText("ACTUALIZA DATOS B.D");
        jButton10ActualizaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActualizaBDActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10ActualizaBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
     
        
    public  void CargandoTablaLaptop2(){
         Laptop usu=null;
      
        ArrayList<Laptop> lsLaptop = Dao.getDaoLaptop().ListarLaptop();
       
        
        if(lsLaptop.size()==-1){
            JOptionPane.showMessageDialog(this,"No hay ningun Usuario Registrado!!");
            
        }
        else{
        
  
        for(int i=0; i<lsLaptop.size(); i++){
              usu=lsLaptop.get(i);
             
                    String b[]= {usu.getSerie(),
                                usu.getMarca(),
                                usu.getModelo(),
                                usu.getDescripcion(),
                                usu.getSO(),
                                usu.getTamano(),
                                String.valueOf(usu.getRam()),
                                String.valueOf(usu.getPrecio()),
                               String.valueOf(usu.getPreferencia())
                                                                }  ;
                      modelo.addRow(b);
            }                  

        }
   }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String marca ;
        if(1000<=Integer.parseInt(jTextField8.getText()) || (5000>=Integer.parseInt(jTextField8.getText()))){
        if(jComboBox4.getSelectedItem().toString().equalsIgnoreCase("Seleccione")||jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Seleccione")||jComboBox2.getSelectedItem().toString().equalsIgnoreCase("Seleccione")||jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Seleccione")){
            JOptionPane.showMessageDialog(this, "Revise todos los campos", "REGISTRO", JOptionPane.ERROR_MESSAGE);
        }else{
            usu.setSerie(jTextField1.getText());
            usu.setMarca(jComboBox1.getSelectedItem().toString());
            usu.setModelo(jTextField3.getText());
            usu.setRam(Integer.parseInt(jComboBox4.getSelectedItem().toString()));
            usu.setPreferencia(0);
            usu.setTamano(jComboBox2.getSelectedItem().toString());
            usu.setDescripcion(jTextArea1.getText());
            usu.setSO(jComboBox3.getSelectedItem().toString());
            usu.setPrecio(Double.parseDouble(jTextField8.getText()));
        

            boolean estado =GestorPrincipal.getGestorLaptop().RegistrarLaptop(usu);
            if(estado){
               JOptionPane.showMessageDialog(this,"Registro Exitoso!!");
               String  a[] = {jTextField1.getText(),
                              jComboBox1.getSelectedItem().toString(),
                              jTextField3.getText(),
                              jTextArea1.getText(),
                              jComboBox3.getSelectedItem().toString(),
                              jComboBox2.getSelectedItem().toString(),
                              jComboBox4.getSelectedItem().toString(),
                              jTextField8.getText(), 
                              0+"",
                              };
              modelo.addRow(a);
              limpiarCampos();
            }
        } }else{
            JOptionPane.showMessageDialog(this, "Rango de precio de laptops [1000-5000]", "REGISTRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         Laptop usu;
         String  BusqueSerie=jTextField10.getText();
         try{
         usu =GestorPrincipal.getGestorLaptop().BuscarLaptop(BusqueSerie);
         ///.-------
         jTextField1.setText(usu.getSerie());
         jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {usu.getMarca()}));
         jTextField3.setText(usu.getModelo());
         jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { usu.getRam()+""}));
         jTextField5.setText(String.valueOf(usu.getPreferencia()));         
         jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { usu.getTamano() }));
         
         jTextArea1.setText(usu.getDescripcion());
         jTextField8.setText(String.valueOf(usu.getPrecio()));
         jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { usu.getSO()}));
         jLabel11.setIcon(PasarImagenIcon(usu.getFotovuelta(),jLabel11));
    }catch(Exception e ){
       
        JOptionPane.showMessageDialog(null,"La serie ingresado no esta registrado \n"
                 + "   en la base de Datos!!!","Error",JOptionPane.ERROR_MESSAGE);
            }        
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 
   boolean estado=false;   
    int filaSelec = jTable2.getSelectedRow();
    String  SerieTabla=  modelo.getValueAt(filaSelec,0).toString();
      //int dniTabla= (int) modelo.getValueAt(filaSelec,0);
      
    if(filaSelec==-1){
       JOptionPane.showMessageDialog(this,"Seleccione una Fila!!","Error",JOptionPane.WARNING_MESSAGE);
      }
    
     
    else {
        try{ 
        int resp=JOptionPane.showConfirmDialog(this,"¿ Desea eliminar la Fila?","Eliminar",JOptionPane.YES_NO_OPTION);
          if(resp == JOptionPane.YES_OPTION){
              modelo.removeRow(filaSelec);
              estado=GestorPrincipal.getGestorLaptop().Eliminar(SerieTabla);
               if(estado){
               JOptionPane.showMessageDialog(this,"Se Elimino !!! la Fila");
               }
              
              }
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"No pudo eliminar la Fila!!!!","Error",JOptionPane.ERROR_MESSAGE);
           }
                  limpiarCampos();
      }
 
 
 
     

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
Reportes.ExportarReportes("laptop.jrxml");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MousePressed
   limpiarCampos();
   this.jButton1.setEnabled(true);
   this.jButton6.setEnabled(true);
   jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png")));    
         
    }//GEN-LAST:event_jTextField10MousePressed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        Laptop usu=null;
        limpiarCampos();
        this.jButton1.setEnabled(false);
        this.jButton6.setEnabled(false);
        try{
            int  fila = jTable2.getSelectedRow();

            String TablaSerie =  jTable2.getValueAt(fila,0).toString();

            usu = GestorPrincipal.getGestorLaptop().BuscarLaptop(TablaSerie);
            jTextField1.setText(usu.getSerie());
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {usu.getMarca()}));
            jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { usu.getRam()+""}));      
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { usu.getTamano() }));
            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { usu.getSO()}));
            jTextField3.setText(usu.getModelo());
            jTextField5.setText(String.valueOf(usu.getPreferencia()));

            jTextArea1.setText(usu.getDescripcion());
            jTextField8.setText(String.valueOf(usu.getPrecio()));
            jLabel11.setIcon(PasarImagenIcon(usu.getFotovuelta(),jLabel11));

        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Selecciones solo una Fila!!","Alerta",JOptionPane.WARNING_MESSAGE);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiarCampos();
        jTextField10.setText("");
        this.jButton1.setEnabled(true);
        this.jButton6.setEnabled(true);
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CargandoImagenProducto(usu, jLabel11, jPanel2);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        boolean modificado=false;
        int fila = jTable2.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Selecciones una fila","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
        else {
            String serieTabla = jTable2.getValueAt(fila,0).toString();
            int ordenLaptop= GestorPrincipal.getGestorLaptop().OrdenLaptop(serieTabla);

            usu.setSerie(jTextField1.getText());
            usu.setMarca(jComboBox1.getSelectedItem().toString());
            usu.setModelo(jTextField3.getText());
            usu.setRam(Integer.parseInt(jComboBox4.getSelectedItem().toString()));
            usu.setTamano(jComboBox2.getSelectedItem().toString());
            usu.setDescripcion(jTextArea1.getText());
            usu.setSO(jComboBox3.getSelectedItem().toString());
            usu.setPrecio(Double.parseDouble(jTextField8.getText()));

            modificado = GestorPrincipal.getGestorLaptop().ModificarLaptopConFoto(usu,ordenLaptop);

            // modificando la tabla de Laptops
            //serie
            jTable2.setValueAt(jTextField1.getText(),fila,0);
            //marca
            jTable2.setValueAt(jComboBox1.getSelectedItem().toString(),fila,1);
            //modelo
            jTable2.setValueAt(jTextField3.getText(),fila,2);
            // descripcion
            jTable2.setValueAt(jTextArea1.getText(),fila,3);
            //so
            jTable2.setValueAt(jComboBox3.getSelectedItem().toString(), fila, 4);
            //tamano
            jTable2.setValueAt(jComboBox2.getSelectedItem().toString(), fila, 5);
            //ram
            jTable2.setValueAt(jComboBox4.getSelectedItem().toString(),fila, 6);
            //precio
            jTable2.setValueAt(jTextField8.getText(),fila,7);
            if(modificado){
                JOptionPane.showMessageDialog(this,"Moficacion de los Datos Exitoso!!!!");}

            // limpiamos todo

            limpiarCampos();
            this.jTextField1.requestFocus();
            jButton6.setEnabled(true);
            jButton1.setEnabled(true);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActualizaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActualizaBDActionPerformed
        // TODO add your handling code here:
       
        boolean modificado=false;
        int fila = jTable2.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Selecciones una fila","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
        else {
            String serieTabla = jTable2.getValueAt(fila,0).toString();
            int ordenLaptop=GestorPrincipal.getGestorLaptop().OrdenLaptop(serieTabla);

            usu.setSerie(jTextField1.getText());
            usu.setMarca(jComboBox1.getSelectedItem().toString());
            usu.setModelo(jTextField3.getText());
            usu.setRam(Integer.parseInt(jComboBox4.getSelectedItem().toString()));
            usu.setTamano(jComboBox2.getSelectedItem().toString());
            usu.setDescripcion(jTextArea1.getText());
            usu.setSO(jComboBox3.getSelectedItem().toString());
            usu.setPrecio(Double.parseDouble(jTextField8.getText()));

            modificado = GestorPrincipal.getGestorLaptop().ModificarLaptopSinFoto(usu,ordenLaptop);

            // modificando la tabla de Laptops
            //serie
            jTable2.setValueAt(jTextField1.getText(),fila,0);
            //marca
            jTable2.setValueAt(jComboBox1.getSelectedItem().toString(),fila,1);
            //modelo
            jTable2.setValueAt(jTextField3.getText(),fila,2);
            // descripcion
            jTable2.setValueAt(jTextArea1.getText(),fila,3);
            //so
            jTable2.setValueAt(jComboBox3.getSelectedItem().toString(), fila, 4);
            //tamano
            jTable2.setValueAt(jComboBox2.getSelectedItem().toString(), fila, 5);
            //ram
            jTable2.setValueAt(jComboBox4.getSelectedItem().toString(),fila, 6);
            //precio
            jTable2.setValueAt(jTextField8.getText(),fila,7);
            if(modificado){
                JOptionPane.showMessageDialog(this,"Moficacion de los Datos Exitoso!!!!");}

            // limpiamos todo

            limpiarCampos();
            this.jTextField1.requestFocus();
            jButton6.setEnabled(true);
            jButton1.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActualizaBDActionPerformed

    private void jRadioButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MousePressed
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton10ActualizaBD.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1MousePressed

    private void jRadioButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MousePressed

        jButton5.setEnabled(false);
        jButton4.setEnabled(false);
        jButton10ActualizaBD.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2MousePressed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
public  void limpiarCampos(){
 this.jTextField1.setText("");
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "toshiba", "asus", "hp", "lenovo" }));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "10''", "12''", "14''", "16''" }));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Linux", "Mac", "Windows" }));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "2", "4", "8", "16"}));
       this.jTextField3.setText("");
       this.jTextField5.setText("");
       this.jTextField8.setText("");
       this.jTextArea1.setText("");
       
       jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png")));
}
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeRegistoLaptops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeRegistoLaptops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeRegistoLaptops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeRegistoLaptops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeRegistoLaptops().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10ActualizaBD;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
